-- ============================================================
-- CES SAVINGS COLUMN MAP - MERGE INSERT
-- Safe to run multiple times - inserts or updates
-- Uses SHEET_NAME + STG_COLUMN_NAME as unique key
-- ============================================================

MERGE INTO CES_SAVINGS_COLUMN_MAP t
USING (
-- ============================================================
-- SAVINGS RESULTS
-- ============================================================
-- Dimension columns
SELECT 'Savings Results' SHEET_NAME, 1  EXCEL_COL_POSITION, '' EXCEL_ROW1_HEADER, '' EXCEL_ROW2_HEADER, 'Vendor Subprogram Key' EXCEL_ROW3_HEADER, '' ROW1_EXPECTED, '' ROW2_EXPECTED, 75 FUZZY_THRESHOLD, 'CES_SAVINGS_STG_ACTUALS' STG_TABLE_NAME, 'TRIENNIUM' STG_COLUMN_NAME, 'CES_SAVINGS_FACT_ACTUALS' FACT_TABLE_NAME, 'TRIENNIUM' FACT_COLUMN_NAME, 'VARCHAR2' DATA_TYPE, 'Y' IS_DIMENSION, 'N' IS_REQUIRED, 'N' IS_STOP_COLUMN, 'Y' IS_ACTIVE FROM DUAL UNION ALL
SELECT 'Savings Results', 2,  '', '', 'Sector',                  '', '',              75, 'CES_SAVINGS_STG_ACTUALS', 'SECTOR',                  'CES_SAVINGS_FACT_ACTUALS', 'SECTOR',                  'VARCHAR2',   'Y', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 3,  '', '', 'Vendor Subprogram Key',   '', '',              75, 'CES_SAVINGS_STG_ACTUALS', 'VENDOR_SUBPROGRAM_KEY',   'CES_SAVINGS_FACT_ACTUALS', 'VENDOR_SUBPROGRAM_KEY',   'VARCHAR2',   'Y', 'Y', 'Y', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 4,  '', '', 'Program',                 '', '',              75, 'CES_SAVINGS_STG_ACTUALS', 'PROGRAM',                 'CES_SAVINGS_FACT_ACTUALS', 'PROGRAM',                 'VARCHAR2',   'Y', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 5,  '', '', 'Subprogram',              '', '',              75, 'CES_SAVINGS_STG_ACTUALS', 'SUBPROGRAM',              'CES_SAVINGS_FACT_ACTUALS', 'SUBPROGRAM',              'VARCHAR2',   'Y', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 6,  '', '', 'Program Year',            '', '',              75, 'CES_SAVINGS_STG_ACTUALS', 'PROGRAM_YEAR',            'CES_SAVINGS_FACT_ACTUALS', 'PROGRAM_YEAR',            'VARCHAR2',   'Y', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 7,  '', '', 'Reporting Period',        '', '',              75, 'CES_SAVINGS_STG_ACTUALS', 'REPORTING_PERIOD',        'CES_SAVINGS_FACT_ACTUALS', 'REPORTING_PERIOD',        'VARCHAR2',   'Y', 'Y', 'N', 'Y' FROM DUAL UNION ALL
-- Financials
SELECT 'Savings Results', 9,  '', 'Financials', '1) Investment - Rebate',  '', 'Financials', 75, 'CES_SAVINGS_STG_ACTUALS', 'INVEST_COST_REBATE',      'CES_SAVINGS_FACT_ACTUALS', 'INVEST_COST_REBATE',      'NUMBER_2',   'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 10, '', 'Financials', '2) Investment - OBR',     '', 'Financials', 75, 'CES_SAVINGS_STG_ACTUALS', 'INVEST_COST_OBR',         'CES_SAVINGS_FACT_ACTUALS', 'INVEST_COST_OBR',         'NUMBER_2',   'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 11, '', 'Financials', '3) Investment - Other',   '', 'Financials', 75, 'CES_SAVINGS_STG_ACTUALS', 'INVEST_COST_OTHER',       'CES_SAVINGS_FACT_ACTUALS', 'INVEST_COST_OTHER',       'NUMBER_2',   'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 12, '', 'Financials', 'Total Investment',         '', 'Financials', 75, 'CES_SAVINGS_STG_ACTUALS', 'TOTAL_INVEST_COST',       'CES_SAVINGS_FACT_ACTUALS', 'TOTAL_INVEST_COST',       'NUMBER_2',   'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
-- Participants
SELECT 'Savings Results', 14, '', 'Participants', 'Total',                  '', 'Participants', 75, 'CES_SAVINGS_STG_ACTUALS', 'PARTICIPANTS_TOTAL',      'CES_SAVINGS_FACT_ACTUALS', 'PARTICIPANTS_TOTAL',      'NUMBER_INT', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 15, '', 'Participants', 'Res LMI or OBC',         '', 'Participants', 75, 'CES_SAVINGS_STG_ACTUALS', 'PARTICIPANTS_RES_LMI_OBC','CES_SAVINGS_FACT_ACTUALS', 'PARTICIPANTS_RES_LMI_OBC','NUMBER_INT', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 16, '', 'Participants', 'Res LMI Only',           '', 'Participants', 75, 'CES_SAVINGS_STG_ACTUALS', 'PARTICIPANTS_RES_LMI_ONLY','CES_SAVINGS_FACT_ACTUALS','PARTICIPANTS_RES_LMI_ONLY','NUMBER_INT','N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 17, '', 'Participants', 'OBC Only (All Projects)', '', 'Participants', 75, 'CES_SAVINGS_STG_ACTUALS', 'PARTICIPANTS_OBC_ONLY',   'CES_SAVINGS_FACT_ACTUALS', 'PARTICIPANTS_OBC_ONLY',   'NUMBER_INT', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 18, '', 'Participants', 'Small Business',          '', 'Participants', 75, 'CES_SAVINGS_STG_ACTUALS', 'PARTICIPANTS_SMALL_BIZ',  'CES_SAVINGS_FACT_ACTUALS', 'PARTICIPANTS_SMALL_BIZ',  'NUMBER_INT', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
-- Gross Site Electric
SELECT 'Savings Results', 20, 'Electric',    'Gross Site Savings (Exclude IEs) TRM Protocol', 'Gross Site Annual Electric Savings - kWh',           'Electric',    'Gross Site Savings (Exclude IEs) TRM Protocol', 75, 'CES_SAVINGS_STG_ACTUALS', 'GROSS_SITE_ELEC_ANNUAL_KWH',       'CES_SAVINGS_FACT_ACTUALS', 'GROSS_SITE_ELEC_ANNUAL_KWH',       'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 21, 'Electric',    'Gross Site Savings (Exclude IEs) TRM Protocol', 'Gross Site Annual Electric Demand Savings - kW',     'Electric',    'Gross Site Savings (Exclude IEs) TRM Protocol', 75, 'CES_SAVINGS_STG_ACTUALS', 'GROSS_SITE_ELEC_DEMAND_KW',        'CES_SAVINGS_FACT_ACTUALS', 'GROSS_SITE_ELEC_DEMAND_KW',        'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 22, 'Electric',    'Gross Site Savings (Exclude IEs) TRM Protocol', 'Gross Site Lifetime Electric Savings - kWh',         'Electric',    'Gross Site Savings (Exclude IEs) TRM Protocol', 75, 'CES_SAVINGS_STG_ACTUALS', 'GROSS_SITE_ELEC_LIFETIME_KWH',     'CES_SAVINGS_FACT_ACTUALS', 'GROSS_SITE_ELEC_LIFETIME_KWH',     'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
-- Gross Site Gas
SELECT 'Savings Results', 23, 'Natural Gas', 'Gross Site Savings (Exclude IEs) TRM Protocol', 'Gross Site Annual Gas Savings - Therms',             'Natural Gas', 'Gross Site Savings (Exclude IEs) TRM Protocol', 75, 'CES_SAVINGS_STG_ACTUALS', 'GROSS_SITE_GAS_ANNUAL_THERMS',     'CES_SAVINGS_FACT_ACTUALS', 'GROSS_SITE_GAS_ANNUAL_THERMS',     'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 24, 'Natural Gas', 'Gross Site Savings (Exclude IEs) TRM Protocol', 'Gross Site Annual Gas Demand Daily Peak Fuel Savings - Therms/day', 'Natural Gas', 'Gross Site Savings (Exclude IEs) TRM Protocol', 75, 'CES_SAVINGS_STG_ACTUALS', 'GROSS_SITE_GAS_DAILY_PEAK_THERMS', 'CES_SAVINGS_FACT_ACTUALS', 'GROSS_SITE_GAS_DAILY_PEAK_THERMS', 'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 25, 'Natural Gas', 'Gross Site Savings (Exclude IEs) TRM Protocol', 'Gross Site Lifetime Gas Savings - Therms',           'Natural Gas', 'Gross Site Savings (Exclude IEs) TRM Protocol', 75, 'CES_SAVINGS_STG_ACTUALS', 'GROSS_SITE_GAS_LIFETIME_THERMS',   'CES_SAVINGS_FACT_ACTUALS', 'GROSS_SITE_GAS_LIFETIME_THERMS',   'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
-- Net Site ISR Electric
SELECT 'Savings Results', 26, 'Electric',    'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 'Net Realized Site Annual Electric Savings - kWh',        'Electric',    'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 75, 'CES_SAVINGS_STG_ACTUALS', 'NET_SITE_ISR_ELEC_ANNUAL_KWH',   'CES_SAVINGS_FACT_ACTUALS', 'NET_SITE_ISR_ELEC_ANNUAL_KWH',   'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 27, 'Electric',    'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 'Net Realized Site Annual Electric Demand Savings - kW',  'Electric',    'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 75, 'CES_SAVINGS_STG_ACTUALS', 'NET_SITE_ISR_ELEC_DEMAND_KW',    'CES_SAVINGS_FACT_ACTUALS', 'NET_SITE_ISR_ELEC_DEMAND_KW',    'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 28, 'Electric',    'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 'Net Realized Site Lifetime Electric Savings - kWh',      'Electric',    'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 75, 'CES_SAVINGS_STG_ACTUALS', 'NET_SITE_ISR_ELEC_LIFETIME_KWH', 'CES_SAVINGS_FACT_ACTUALS', 'NET_SITE_ISR_ELEC_LIFETIME_KWH', 'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
-- Net Site ISR Gas
SELECT 'Savings Results', 29, 'Natural Gas', 'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 'Net Realized Site Annual Gas Savings - Therms',          'Natural Gas', 'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 75, 'CES_SAVINGS_STG_ACTUALS', 'NET_SITE_ISR_GAS_ANNUAL_THERMS',      'CES_SAVINGS_FACT_ACTUALS', 'NET_SITE_ISR_GAS_ANNUAL_THERMS',      'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 30, 'Natural Gas', 'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 'Net Realized Site Annual Gas Demand Daily Peak Fuel Savings - Therms/day', 'Natural Gas', 'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 75, 'CES_SAVINGS_STG_ACTUALS', 'NET_SITE_ISR_GAS_DAILY_PEAK_THERMS',  'CES_SAVINGS_FACT_ACTUALS', 'NET_SITE_ISR_GAS_DAILY_PEAK_THERMS',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 31, 'Natural Gas', 'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 'Net Realized Site Lifetime Gas Savings - Therms',        'Natural Gas', 'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 75, 'CES_SAVINGS_STG_ACTUALS', 'NET_SITE_ISR_GAS_LIFETIME_THERMS',    'CES_SAVINGS_FACT_ACTUALS', 'NET_SITE_ISR_GAS_LIFETIME_THERMS',    'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
-- Negative IEs
SELECT 'Savings Results', 32, 'Electric',    'Negative Interactive Effects (IEs)', 'Net Realized Site Annual Electric Savings - IEs Only',   'Electric',    'Negative Interactive Effects (IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'NEG_IE_ELEC_ANNUAL_KWH',   'CES_SAVINGS_FACT_ACTUALS', 'NEG_IE_ELEC_ANNUAL_KWH',   'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 33, 'Electric',    'Negative Interactive Effects (IEs)', 'Net Realized Site Lifetime Electric Savings - IEs Only', 'Electric',    'Negative Interactive Effects (IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'NEG_IE_ELEC_LIFETIME_KWH', 'CES_SAVINGS_FACT_ACTUALS', 'NEG_IE_ELEC_LIFETIME_KWH', 'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 34, 'Natural Gas', 'Negative Interactive Effects (IEs)', 'Net Realized Site Annual Gas Savings - IEs Only',        'Natural Gas', 'Negative Interactive Effects (IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'NEG_IE_GAS_ANNUAL_THERMS', 'CES_SAVINGS_FACT_ACTUALS', 'NEG_IE_GAS_ANNUAL_THERMS', 'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 35, 'Natural Gas', 'Negative Interactive Effects (IEs)', 'Net Realized Site Lifetime Gas Savings - IEs Only',     'Natural Gas', 'Negative Interactive Effects (IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'NEG_IE_GAS_LIFETIME_THERMS','CES_SAVINGS_FACT_ACTUALS', 'NEG_IE_GAS_LIFETIME_THERMS','NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
-- Total Net Site
SELECT 'Savings Results', 36, 'Electric',    'Total Net Realized Site Savings (Include Negative IEs)', 'Net Realized Site Annual Electric Savings - kWh',   'Electric',    'Total Net Realized Site Savings (Include Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'TOTAL_NET_SITE_ELEC_ANNUAL_KWH',   'CES_SAVINGS_FACT_ACTUALS', 'TOTAL_NET_SITE_ELEC_ANNUAL_KWH',   'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 37, 'Electric',    'Total Net Realized Site Savings (Include Negative IEs)', 'Net Realized Site Lifetime Electric Savings - kWh', 'Electric',    'Total Net Realized Site Savings (Include Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'TOTAL_NET_SITE_ELEC_LIFETIME_KWH', 'CES_SAVINGS_FACT_ACTUALS', 'TOTAL_NET_SITE_ELEC_LIFETIME_KWH', 'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 38, 'Natural Gas', 'Total Net Realized Site Savings (Include Negative IEs)', 'Net Realized Site Annual Gas Savings - Therms',     'Natural Gas', 'Total Net Realized Site Savings (Include Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'TOTAL_NET_SITE_GAS_ANNUAL_THERMS', 'CES_SAVINGS_FACT_ACTUALS', 'TOTAL_NET_SITE_GAS_ANNUAL_THERMS', 'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 39, 'Natural Gas', 'Total Net Realized Site Savings (Include Negative IEs)', 'Net Realized Site Lifetime Gas Savings - Therms',   'Natural Gas', 'Total Net Realized Site Savings (Include Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'TOTAL_NET_SITE_GAS_LIFETIME_THERMS','CES_SAVINGS_FACT_ACTUALS', 'TOTAL_NET_SITE_GAS_LIFETIME_THERMS','NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
-- Net Source
SELECT 'Savings Results', 40, 'Electric',          'Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 'Net Realized Source Annual Electric Savings - MMBtu',   'Electric',          'Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 75, 'CES_SAVINGS_STG_ACTUALS', 'NET_SRC_ELEC_ANNUAL_MMBTU',   'CES_SAVINGS_FACT_ACTUALS', 'NET_SRC_ELEC_ANNUAL_MMBTU',   'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 41, 'Electric',          'Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 'Net Realized Source Lifetime Electric Savings - MMBtu', 'Electric',          'Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 75, 'CES_SAVINGS_STG_ACTUALS', 'NET_SRC_ELEC_LIFETIME_MMBTU', 'CES_SAVINGS_FACT_ACTUALS', 'NET_SRC_ELEC_LIFETIME_MMBTU', 'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 42, 'Natural Gas',       'Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 'Net Realized Source Annual Gas Savings - MMBtu',        'Natural Gas',       'Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 75, 'CES_SAVINGS_STG_ACTUALS', 'NET_SRC_GAS_ANNUAL_MMBTU',    'CES_SAVINGS_FACT_ACTUALS', 'NET_SRC_GAS_ANNUAL_MMBTU',    'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 43, 'Natural Gas',       'Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 'Net Realized Source Lifetime Gas Savings - MMBtu',      'Natural Gas',       'Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 75, 'CES_SAVINGS_STG_ACTUALS', 'NET_SRC_GAS_LIFETIME_MMBTU',  'CES_SAVINGS_FACT_ACTUALS', 'NET_SRC_GAS_LIFETIME_MMBTU',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 44, 'Elec and Gas Total','Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 'Net Realized Source Annual Savings - MMBtu',            'Elec and Gas Total','Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 75, 'CES_SAVINGS_STG_ACTUALS', 'NET_SRC_ANNUAL_MMBTU',        'CES_SAVINGS_FACT_ACTUALS', 'NET_SRC_ANNUAL_MMBTU',        'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 45, 'Elec and Gas Total','Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 'Net Realized Source Lifetime Savings - MMBtu',          'Elec and Gas Total','Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 75, 'CES_SAVINGS_STG_ACTUALS', 'NET_SRC_LIFETIME_MMBTU',      'CES_SAVINGS_FACT_ACTUALS', 'NET_SRC_LIFETIME_MMBTU',      'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
-- Target Segments Source
SELECT 'Savings Results', 46, 'Residential LMI or OBC',  'Target Segments - Net Realized Source Savings', 'LMI OBC Annual Energy Savings (Net Source MMBtu)',    'Residential LMI or OBC',  'Target Segments - Net Realized Source Savings', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_LMI_OBC_ANNUAL_MMBTU',   'CES_SAVINGS_FACT_ACTUALS', 'SEG_LMI_OBC_ANNUAL_MMBTU',   'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 47, 'Residential LMI or OBC',  'Target Segments - Net Realized Source Savings', 'LMI OBC Lifetime Energy Savings (Net Source MMBtu)',  'Residential LMI or OBC',  'Target Segments - Net Realized Source Savings', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_LMI_OBC_LIFETIME_MMBTU', 'CES_SAVINGS_FACT_ACTUALS', 'SEG_LMI_OBC_LIFETIME_MMBTU', 'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 48, 'Residential LMI Only',    'Target Segments - Net Realized Source Savings', 'LMI Annual Energy Savings (Net Source MMBtu)',        'Residential LMI Only',    'Target Segments - Net Realized Source Savings', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_LMI_ANNUAL_MMBTU',       'CES_SAVINGS_FACT_ACTUALS', 'SEG_LMI_ANNUAL_MMBTU',       'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 49, 'Residential LMI Only',    'Target Segments - Net Realized Source Savings', 'LMI Lifetime Energy Savings (Net Source MMBtu)',      'Residential LMI Only',    'Target Segments - Net Realized Source Savings', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_LMI_LIFETIME_MMBTU',     'CES_SAVINGS_FACT_ACTUALS', 'SEG_LMI_LIFETIME_MMBTU',     'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 50, 'OBC Only (All Projects)', 'Target Segments - Net Realized Source Savings', 'OBC Annual Energy Savings (Net Source MMBtu)',        'OBC Only (All Projects)', 'Target Segments - Net Realized Source Savings', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_OBC_ANNUAL_MMBTU',       'CES_SAVINGS_FACT_ACTUALS', 'SEG_OBC_ANNUAL_MMBTU',       'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 51, 'OBC Only (All Projects)', 'Target Segments - Net Realized Source Savings', 'OBC Lifetime Energy Savings (Net Source MMBtu)',      'OBC Only (All Projects)', 'Target Segments - Net Realized Source Savings', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_OBC_LIFETIME_MMBTU',     'CES_SAVINGS_FACT_ACTUALS', 'SEG_OBC_LIFETIME_MMBTU',     'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 52, 'Small Business',          'Target Segments - Net Realized Source Savings', 'Small Business Annual Energy Savings (Net Source MMBtu)',  'Small Business', 'Target Segments - Net Realized Source Savings', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_SMALL_BIZ_ANNUAL_MMBTU',   'CES_SAVINGS_FACT_ACTUALS', 'SEG_SMALL_BIZ_ANNUAL_MMBTU',   'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 53, 'Small Business',          'Target Segments - Net Realized Source Savings', 'Small Business Lifetime Energy Savings (Net Source MMBtu)', 'Small Business', 'Target Segments - Net Realized Source Savings', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_SMALL_BIZ_LIFETIME_MMBTU', 'CES_SAVINGS_FACT_ACTUALS', 'SEG_SMALL_BIZ_LIFETIME_MMBTU', 'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 54, 'Multifamily',             'Target Segments - Net Realized Source Savings', 'Multifamily Annual Energy Savings (Net Source MMBtu)',    'Multifamily',   'Target Segments - Net Realized Source Savings', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_MULTIFAMILY_ANNUAL_MMBTU',   'CES_SAVINGS_FACT_ACTUALS', 'SEG_MULTIFAMILY_ANNUAL_MMBTU',   'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 55, 'Multifamily',             'Target Segments - Net Realized Source Savings', 'Multifamily Lifetime Energy Savings (Net Source MMBtu)',  'Multifamily',   'Target Segments - Net Realized Source Savings', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_MULTIFAMILY_LIFETIME_MMBTU', 'CES_SAVINGS_FACT_ACTUALS', 'SEG_MULTIFAMILY_LIFETIME_MMBTU', 'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
-- Target Segments Site - Residential LMI or OBC
SELECT 'Savings Results', 56, 'Residential LMI or OBC', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Annual Electric Savings - kWh',   'Residential LMI or OBC', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_RES_LMI_OBC_ELEC_ANNUAL_KWH',    'CES_SAVINGS_FACT_ACTUALS', 'SEG_RES_LMI_OBC_ELEC_ANNUAL_KWH',    'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 57, 'Residential LMI or OBC', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Lifetime Electric Savings - kWh', 'Residential LMI or OBC', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_RES_LMI_OBC_ELEC_LIFETIME_KWH',  'CES_SAVINGS_FACT_ACTUALS', 'SEG_RES_LMI_OBC_ELEC_LIFETIME_KWH',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 58, 'Residential LMI or OBC', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Annual Gas Savings - Therms',     'Residential LMI or OBC', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_RES_LMI_OBC_GAS_ANNUAL_THERMS',  'CES_SAVINGS_FACT_ACTUALS', 'SEG_RES_LMI_OBC_GAS_ANNUAL_THERMS',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 59, 'Residential LMI or OBC', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Lifetime Gas Savings - Therms',   'Residential LMI or OBC', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_RES_LMI_OBC_GAS_LIFETIME_THERMS','CES_SAVINGS_FACT_ACTUALS', 'SEG_RES_LMI_OBC_GAS_LIFETIME_THERMS','NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
-- Target Segments Site - Residential LMI Only
SELECT 'Savings Results', 60, 'Residential LMI Only',   'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Annual Electric Savings - kWh',   'Residential LMI Only',   'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_RES_LMI_ELEC_ANNUAL_KWH',    'CES_SAVINGS_FACT_ACTUALS', 'SEG_RES_LMI_ELEC_ANNUAL_KWH',    'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 61, 'Residential LMI Only',   'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Lifetime Electric Savings - kWh', 'Residential LMI Only',   'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_RES_LMI_ELEC_LIFETIME_KWH',  'CES_SAVINGS_FACT_ACTUALS', 'SEG_RES_LMI_ELEC_LIFETIME_KWH',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 62, 'Residential LMI Only',   'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Annual Gas Savings - Therms',     'Residential LMI Only',   'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_RES_LMI_GAS_ANNUAL_THERMS',  'CES_SAVINGS_FACT_ACTUALS', 'SEG_RES_LMI_GAS_ANNUAL_THERMS',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 63, 'Residential LMI Only',   'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Lifetime Gas Savings - Therms',   'Residential LMI Only',   'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_RES_LMI_GAS_LIFETIME_THERMS','CES_SAVINGS_FACT_ACTUALS', 'SEG_RES_LMI_GAS_LIFETIME_THERMS','NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
-- Target Segments Site - OBC Only
SELECT 'Savings Results', 64, 'OBC Only (All Projects)', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Annual Electric Savings - kWh',   'OBC Only (All Projects)', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_OBC_ELEC_ANNUAL_KWH',    'CES_SAVINGS_FACT_ACTUALS', 'SEG_OBC_ELEC_ANNUAL_KWH',    'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 65, 'OBC Only (All Projects)', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Lifetime Electric Savings - kWh', 'OBC Only (All Projects)', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_OBC_ELEC_LIFETIME_KWH',  'CES_SAVINGS_FACT_ACTUALS', 'SEG_OBC_ELEC_LIFETIME_KWH',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 66, 'OBC Only (All Projects)', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Annual Gas Savings - Therms',     'OBC Only (All Projects)', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_OBC_GAS_ANNUAL_THERMS',  'CES_SAVINGS_FACT_ACTUALS', 'SEG_OBC_GAS_ANNUAL_THERMS',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 67, 'OBC Only (All Projects)', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Lifetime Gas Savings - Therms',   'OBC Only (All Projects)', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_OBC_GAS_LIFETIME_THERMS','CES_SAVINGS_FACT_ACTUALS', 'SEG_OBC_GAS_LIFETIME_THERMS','NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
-- Target Segments Site - Small Business
SELECT 'Savings Results', 68, 'Small Business', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Annual Electric Savings - kWh',   'Small Business', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_SMALL_BIZ_ELEC_ANNUAL_KWH',    'CES_SAVINGS_FACT_ACTUALS', 'SEG_SMALL_BIZ_ELEC_ANNUAL_KWH',    'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 69, 'Small Business', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Lifetime Electric Savings - kWh', 'Small Business', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_SMALL_BIZ_ELEC_LIFETIME_KWH',  'CES_SAVINGS_FACT_ACTUALS', 'SEG_SMALL_BIZ_ELEC_LIFETIME_KWH',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 70, 'Small Business', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Annual Gas Savings - Therms',     'Small Business', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_SMALL_BIZ_GAS_ANNUAL_THERMS',  'CES_SAVINGS_FACT_ACTUALS', 'SEG_SMALL_BIZ_GAS_ANNUAL_THERMS',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 71, 'Small Business', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Lifetime Gas Savings - Therms',   'Small Business', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_SMALL_BIZ_GAS_LIFETIME_THERMS','CES_SAVINGS_FACT_ACTUALS', 'SEG_SMALL_BIZ_GAS_LIFETIME_THERMS','NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
-- Target Segments Site - Multifamily
SELECT 'Savings Results', 72, 'Multifamily', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Annual Electric Savings - kWh',   'Multifamily', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_MULTIFAMILY_ELEC_ANNUAL_KWH',    'CES_SAVINGS_FACT_ACTUALS', 'SEG_MULTIFAMILY_ELEC_ANNUAL_KWH',    'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 73, 'Multifamily', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Lifetime Electric Savings - kWh', 'Multifamily', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_MULTIFAMILY_ELEC_LIFETIME_KWH',  'CES_SAVINGS_FACT_ACTUALS', 'SEG_MULTIFAMILY_ELEC_LIFETIME_KWH',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 74, 'Multifamily', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Annual Gas Savings - Therms',     'Multifamily', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_MULTIFAMILY_GAS_ANNUAL_THERMS',  'CES_SAVINGS_FACT_ACTUALS', 'SEG_MULTIFAMILY_GAS_ANNUAL_THERMS',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Results', 75, 'Multifamily', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Lifetime Gas Savings - Therms',   'Multifamily', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_ACTUALS', 'SEG_MULTIFAMILY_GAS_LIFETIME_THERMS','CES_SAVINGS_FACT_ACTUALS', 'SEG_MULTIFAMILY_GAS_LIFETIME_THERMS','NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
-- ============================================================
-- SAVINGS FORECAST
-- Columns 1-6 same as actuals
-- Column 7 = Forecast Period (replaces Reporting Period)
-- Column 8 = Confidence Level (extra)
-- All metric columns shift +2 from actuals
-- ============================================================
SELECT 'Savings Forecast', 1,  '', '', 'Triennium',              '', '', 75, 'CES_SAVINGS_STG_FORECAST', 'TRIENNIUM',             'CES_SAVINGS_FACT_FORECAST', 'TRIENNIUM',             'VARCHAR2',   'Y', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 2,  '', '', 'Sector',                  '', '', 75, 'CES_SAVINGS_STG_FORECAST', 'SECTOR',                'CES_SAVINGS_FACT_FORECAST', 'SECTOR',                'VARCHAR2',   'Y', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 3,  '', '', 'Vendor Subprogram Key',   '', '', 75, 'CES_SAVINGS_STG_FORECAST', 'VENDOR_SUBPROGRAM_KEY', 'CES_SAVINGS_FACT_FORECAST', 'VENDOR_SUBPROGRAM_KEY', 'VARCHAR2',   'Y', 'Y', 'Y', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 4,  '', '', 'Program',                 '', '', 75, 'CES_SAVINGS_STG_FORECAST', 'PROGRAM',               'CES_SAVINGS_FACT_FORECAST', 'PROGRAM',               'VARCHAR2',   'Y', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 5,  '', '', 'Subprogram',              '', '', 75, 'CES_SAVINGS_STG_FORECAST', 'SUBPROGRAM',            'CES_SAVINGS_FACT_FORECAST', 'SUBPROGRAM',            'VARCHAR2',   'Y', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 6,  '', '', 'Program Year',            '', '', 75, 'CES_SAVINGS_STG_FORECAST', 'PROGRAM_YEAR',          'CES_SAVINGS_FACT_FORECAST', 'PROGRAM_YEAR',          'VARCHAR2',   'Y', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 7,  '', '', 'Forecast Period',         '', '', 75, 'CES_SAVINGS_STG_FORECAST', 'FORECAST_PERIOD',       'CES_SAVINGS_FACT_FORECAST', 'FORECAST_PERIOD',       'VARCHAR2',   'Y', 'Y', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 8,  '', '', 'Confidence Level',        '', '', 75, 'CES_SAVINGS_STG_FORECAST', 'CONFIDENCE_LEVEL',      'CES_SAVINGS_FACT_FORECAST', 'CONFIDENCE_LEVEL',      'VARCHAR2',   'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 11, '', 'Financials', '1) Investment - Rebate',  '', 'Financials', 75, 'CES_SAVINGS_STG_FORECAST', 'INVEST_COST_REBATE', 'CES_SAVINGS_FACT_FORECAST', 'INVEST_COST_REBATE', 'NUMBER_2', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 12, '', 'Financials', '2) Investment - OBR',     '', 'Financials', 75, 'CES_SAVINGS_STG_FORECAST', 'INVEST_COST_OBR',    'CES_SAVINGS_FACT_FORECAST', 'INVEST_COST_OBR',    'NUMBER_2', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 13, '', 'Financials', '3) Investment - Other',   '', 'Financials', 75, 'CES_SAVINGS_STG_FORECAST', 'INVEST_COST_OTHER',  'CES_SAVINGS_FACT_FORECAST', 'INVEST_COST_OTHER',  'NUMBER_2', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 14, '', 'Financials', 'Total Investment',         '', 'Financials', 75, 'CES_SAVINGS_STG_FORECAST', 'TOTAL_INVEST_COST',  'CES_SAVINGS_FACT_FORECAST', 'TOTAL_INVEST_COST',  'NUMBER_2', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 16, '', 'Participants', 'Total',                  '', 'Participants', 75, 'CES_SAVINGS_STG_FORECAST', 'PARTICIPANTS_TOTAL',       'CES_SAVINGS_FACT_FORECAST', 'PARTICIPANTS_TOTAL',       'NUMBER_INT', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 17, '', 'Participants', 'Res LMI or OBC',         '', 'Participants', 75, 'CES_SAVINGS_STG_FORECAST', 'PARTICIPANTS_RES_LMI_OBC', 'CES_SAVINGS_FACT_FORECAST', 'PARTICIPANTS_RES_LMI_OBC', 'NUMBER_INT', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 18, '', 'Participants', 'Res LMI Only',           '', 'Participants', 75, 'CES_SAVINGS_STG_FORECAST', 'PARTICIPANTS_RES_LMI_ONLY','CES_SAVINGS_FACT_FORECAST', 'PARTICIPANTS_RES_LMI_ONLY','NUMBER_INT', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 19, '', 'Participants', 'OBC Only (All Projects)', '', 'Participants', 75, 'CES_SAVINGS_STG_FORECAST', 'PARTICIPANTS_OBC_ONLY',    'CES_SAVINGS_FACT_FORECAST', 'PARTICIPANTS_OBC_ONLY',    'NUMBER_INT', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 20, '', 'Participants', 'Small Business',          '', 'Participants', 75, 'CES_SAVINGS_STG_FORECAST', 'PARTICIPANTS_SMALL_BIZ',   'CES_SAVINGS_FACT_FORECAST', 'PARTICIPANTS_SMALL_BIZ',   'NUMBER_INT', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 22, 'Electric',    'Gross Site Savings (Exclude IEs) TRM Protocol', 'Gross Site Annual Electric Savings - kWh',           'Electric',    'Gross Site Savings (Exclude IEs) TRM Protocol', 75, 'CES_SAVINGS_STG_FORECAST', 'GROSS_SITE_ELEC_ANNUAL_KWH',       'CES_SAVINGS_FACT_FORECAST', 'GROSS_SITE_ELEC_ANNUAL_KWH',       'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 23, 'Electric',    'Gross Site Savings (Exclude IEs) TRM Protocol', 'Gross Site Annual Electric Demand Savings - kW',     'Electric',    'Gross Site Savings (Exclude IEs) TRM Protocol', 75, 'CES_SAVINGS_STG_FORECAST', 'GROSS_SITE_ELEC_DEMAND_KW',        'CES_SAVINGS_FACT_FORECAST', 'GROSS_SITE_ELEC_DEMAND_KW',        'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 24, 'Electric',    'Gross Site Savings (Exclude IEs) TRM Protocol', 'Gross Site Lifetime Electric Savings - kWh',         'Electric',    'Gross Site Savings (Exclude IEs) TRM Protocol', 75, 'CES_SAVINGS_STG_FORECAST', 'GROSS_SITE_ELEC_LIFETIME_KWH',     'CES_SAVINGS_FACT_FORECAST', 'GROSS_SITE_ELEC_LIFETIME_KWH',     'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 25, 'Natural Gas', 'Gross Site Savings (Exclude IEs) TRM Protocol', 'Gross Site Annual Gas Savings - Therms',             'Natural Gas', 'Gross Site Savings (Exclude IEs) TRM Protocol', 75, 'CES_SAVINGS_STG_FORECAST', 'GROSS_SITE_GAS_ANNUAL_THERMS',     'CES_SAVINGS_FACT_FORECAST', 'GROSS_SITE_GAS_ANNUAL_THERMS',     'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 26, 'Natural Gas', 'Gross Site Savings (Exclude IEs) TRM Protocol', 'Gross Site Annual Gas Demand Daily Peak Fuel Savings - Therms/day', 'Natural Gas', 'Gross Site Savings (Exclude IEs) TRM Protocol', 75, 'CES_SAVINGS_STG_FORECAST', 'GROSS_SITE_GAS_DAILY_PEAK_THERMS', 'CES_SAVINGS_FACT_FORECAST', 'GROSS_SITE_GAS_DAILY_PEAK_THERMS', 'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 27, 'Natural Gas', 'Gross Site Savings (Exclude IEs) TRM Protocol', 'Gross Site Lifetime Gas Savings - Therms',           'Natural Gas', 'Gross Site Savings (Exclude IEs) TRM Protocol', 75, 'CES_SAVINGS_STG_FORECAST', 'GROSS_SITE_GAS_LIFETIME_THERMS',   'CES_SAVINGS_FACT_FORECAST', 'GROSS_SITE_GAS_LIFETIME_THERMS',   'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 28, 'Electric',    'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 'Net Realized Site Annual Electric Savings - kWh',        'Electric',    'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 75, 'CES_SAVINGS_STG_FORECAST', 'NET_SITE_ISR_ELEC_ANNUAL_KWH',        'CES_SAVINGS_FACT_FORECAST', 'NET_SITE_ISR_ELEC_ANNUAL_KWH',        'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 29, 'Electric',    'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 'Net Realized Site Annual Electric Demand Savings - kW',  'Electric',    'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 75, 'CES_SAVINGS_STG_FORECAST', 'NET_SITE_ISR_ELEC_DEMAND_KW',         'CES_SAVINGS_FACT_FORECAST', 'NET_SITE_ISR_ELEC_DEMAND_KW',         'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 30, 'Electric',    'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 'Net Realized Site Lifetime Electric Savings - kWh',      'Electric',    'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 75, 'CES_SAVINGS_STG_FORECAST', 'NET_SITE_ISR_ELEC_LIFETIME_KWH',      'CES_SAVINGS_FACT_FORECAST', 'NET_SITE_ISR_ELEC_LIFETIME_KWH',      'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 31, 'Natural Gas', 'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 'Net Realized Site Annual Gas Savings - Therms',          'Natural Gas', 'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 75, 'CES_SAVINGS_STG_FORECAST', 'NET_SITE_ISR_GAS_ANNUAL_THERMS',      'CES_SAVINGS_FACT_FORECAST', 'NET_SITE_ISR_GAS_ANNUAL_THERMS',      'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 32, 'Natural Gas', 'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 'Net Realized Site Annual Gas Demand Daily Peak Fuel Savings - Therms/day', 'Natural Gas', 'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 75, 'CES_SAVINGS_STG_FORECAST', 'NET_SITE_ISR_GAS_DAILY_PEAK_THERMS',  'CES_SAVINGS_FACT_FORECAST', 'NET_SITE_ISR_GAS_DAILY_PEAK_THERMS',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 33, 'Natural Gas', 'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 'Net Realized Site Lifetime Gas Savings - Therms',        'Natural Gas', 'Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR', 75, 'CES_SAVINGS_STG_FORECAST', 'NET_SITE_ISR_GAS_LIFETIME_THERMS',    'CES_SAVINGS_FACT_FORECAST', 'NET_SITE_ISR_GAS_LIFETIME_THERMS',    'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 34, 'Electric',    'Negative Interactive Effects (IEs)', 'Net Realized Site Annual Electric Savings - IEs Only',   'Electric',    'Negative Interactive Effects (IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'NEG_IE_ELEC_ANNUAL_KWH',    'CES_SAVINGS_FACT_FORECAST', 'NEG_IE_ELEC_ANNUAL_KWH',    'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 35, 'Electric',    'Negative Interactive Effects (IEs)', 'Net Realized Site Lifetime Electric Savings - IEs Only', 'Electric',    'Negative Interactive Effects (IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'NEG_IE_ELEC_LIFETIME_KWH',  'CES_SAVINGS_FACT_FORECAST', 'NEG_IE_ELEC_LIFETIME_KWH',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 36, 'Natural Gas', 'Negative Interactive Effects (IEs)', 'Net Realized Site Annual Gas Savings - IEs Only',        'Natural Gas', 'Negative Interactive Effects (IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'NEG_IE_GAS_ANNUAL_THERMS',  'CES_SAVINGS_FACT_FORECAST', 'NEG_IE_GAS_ANNUAL_THERMS',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 37, 'Natural Gas', 'Negative Interactive Effects (IEs)', 'Net Realized Site Lifetime Gas Savings - IEs Only',     'Natural Gas', 'Negative Interactive Effects (IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'NEG_IE_GAS_LIFETIME_THERMS','CES_SAVINGS_FACT_FORECAST', 'NEG_IE_GAS_LIFETIME_THERMS','NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 38, 'Electric',    'Total Net Realized Site Savings (Include Negative IEs)', 'Net Realized Site Annual Electric Savings - kWh',   'Electric',    'Total Net Realized Site Savings (Include Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'TOTAL_NET_SITE_ELEC_ANNUAL_KWH',    'CES_SAVINGS_FACT_FORECAST', 'TOTAL_NET_SITE_ELEC_ANNUAL_KWH',    'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 39, 'Electric',    'Total Net Realized Site Savings (Include Negative IEs)', 'Net Realized Site Lifetime Electric Savings - kWh', 'Electric',    'Total Net Realized Site Savings (Include Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'TOTAL_NET_SITE_ELEC_LIFETIME_KWH',  'CES_SAVINGS_FACT_FORECAST', 'TOTAL_NET_SITE_ELEC_LIFETIME_KWH',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 40, 'Natural Gas', 'Total Net Realized Site Savings (Include Negative IEs)', 'Net Realized Site Annual Gas Savings - Therms',     'Natural Gas', 'Total Net Realized Site Savings (Include Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'TOTAL_NET_SITE_GAS_ANNUAL_THERMS',  'CES_SAVINGS_FACT_FORECAST', 'TOTAL_NET_SITE_GAS_ANNUAL_THERMS',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 41, 'Natural Gas', 'Total Net Realized Site Savings (Include Negative IEs)', 'Net Realized Site Lifetime Gas Savings - Therms',   'Natural Gas', 'Total Net Realized Site Savings (Include Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'TOTAL_NET_SITE_GAS_LIFETIME_THERMS','CES_SAVINGS_FACT_FORECAST', 'TOTAL_NET_SITE_GAS_LIFETIME_THERMS','NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 42, 'Electric',          'Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 'Net Realized Source Annual Electric Savings - MMBtu',   'Electric',          'Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 75, 'CES_SAVINGS_STG_FORECAST', 'NET_SRC_ELEC_ANNUAL_MMBTU',   'CES_SAVINGS_FACT_FORECAST', 'NET_SRC_ELEC_ANNUAL_MMBTU',   'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 43, 'Electric',          'Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 'Net Realized Source Lifetime Electric Savings - MMBtu', 'Electric',          'Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 75, 'CES_SAVINGS_STG_FORECAST', 'NET_SRC_ELEC_LIFETIME_MMBTU', 'CES_SAVINGS_FACT_FORECAST', 'NET_SRC_ELEC_LIFETIME_MMBTU', 'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 44, 'Natural Gas',       'Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 'Net Realized Source Annual Gas Savings - MMBtu',        'Natural Gas',       'Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 75, 'CES_SAVINGS_STG_FORECAST', 'NET_SRC_GAS_ANNUAL_MMBTU',    'CES_SAVINGS_FACT_FORECAST', 'NET_SRC_GAS_ANNUAL_MMBTU',    'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 45, 'Natural Gas',       'Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 'Net Realized Source Lifetime Gas Savings - MMBtu',      'Natural Gas',       'Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 75, 'CES_SAVINGS_STG_FORECAST', 'NET_SRC_GAS_LIFETIME_MMBTU',  'CES_SAVINGS_FACT_FORECAST', 'NET_SRC_GAS_LIFETIME_MMBTU',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 46, 'Elec and Gas Total','Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 'Net Realized Source Annual Savings - MMBtu',            'Elec and Gas Total','Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 75, 'CES_SAVINGS_STG_FORECAST', 'NET_SRC_ANNUAL_MMBTU',        'CES_SAVINGS_FACT_FORECAST', 'NET_SRC_ANNUAL_MMBTU',        'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 47, 'Elec and Gas Total','Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 'Net Realized Source Lifetime Savings - MMBtu',          'Elec and Gas Total','Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion', 75, 'CES_SAVINGS_STG_FORECAST', 'NET_SRC_LIFETIME_MMBTU',      'CES_SAVINGS_FACT_FORECAST', 'NET_SRC_LIFETIME_MMBTU',      'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 48, 'Residential LMI or OBC',  'Target Segments - Net Realized Source Savings', 'LMI OBC Annual Energy Savings (Net Source MMBtu)',    'Residential LMI or OBC',  'Target Segments - Net Realized Source Savings', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_LMI_OBC_ANNUAL_MMBTU',   'CES_SAVINGS_FACT_FORECAST', 'SEG_LMI_OBC_ANNUAL_MMBTU',   'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 49, 'Residential LMI or OBC',  'Target Segments - Net Realized Source Savings', 'LMI OBC Lifetime Energy Savings (Net Source MMBtu)',  'Residential LMI or OBC',  'Target Segments - Net Realized Source Savings', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_LMI_OBC_LIFETIME_MMBTU', 'CES_SAVINGS_FACT_FORECAST', 'SEG_LMI_OBC_LIFETIME_MMBTU', 'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 50, 'Residential LMI Only',    'Target Segments - Net Realized Source Savings', 'LMI Annual Energy Savings (Net Source MMBtu)',        'Residential LMI Only',    'Target Segments - Net Realized Source Savings', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_LMI_ANNUAL_MMBTU',       'CES_SAVINGS_FACT_FORECAST', 'SEG_LMI_ANNUAL_MMBTU',       'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 51, 'Residential LMI Only',    'Target Segments - Net Realized Source Savings', 'LMI Lifetime Energy Savings (Net Source MMBtu)',      'Residential LMI Only',    'Target Segments - Net Realized Source Savings', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_LMI_LIFETIME_MMBTU',     'CES_SAVINGS_FACT_FORECAST', 'SEG_LMI_LIFETIME_MMBTU',     'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 52, 'OBC Only (All Projects)', 'Target Segments - Net Realized Source Savings', 'OBC Annual Energy Savings (Net Source MMBtu)',        'OBC Only (All Projects)', 'Target Segments - Net Realized Source Savings', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_OBC_ANNUAL_MMBTU',       'CES_SAVINGS_FACT_FORECAST', 'SEG_OBC_ANNUAL_MMBTU',       'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 53, 'OBC Only (All Projects)', 'Target Segments - Net Realized Source Savings', 'OBC Lifetime Energy Savings (Net Source MMBtu)',      'OBC Only (All Projects)', 'Target Segments - Net Realized Source Savings', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_OBC_LIFETIME_MMBTU',     'CES_SAVINGS_FACT_FORECAST', 'SEG_OBC_LIFETIME_MMBTU',     'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 54, 'Small Business',          'Target Segments - Net Realized Source Savings', 'Small Business Annual Energy Savings (Net Source MMBtu)',  'Small Business', 'Target Segments - Net Realized Source Savings', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_SMALL_BIZ_ANNUAL_MMBTU',   'CES_SAVINGS_FACT_FORECAST', 'SEG_SMALL_BIZ_ANNUAL_MMBTU',   'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 55, 'Small Business',          'Target Segments - Net Realized Source Savings', 'Small Business Lifetime Energy Savings (Net Source MMBtu)', 'Small Business', 'Target Segments - Net Realized Source Savings', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_SMALL_BIZ_LIFETIME_MMBTU', 'CES_SAVINGS_FACT_FORECAST', 'SEG_SMALL_BIZ_LIFETIME_MMBTU', 'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 56, 'Multifamily',             'Target Segments - Net Realized Source Savings', 'Multifamily Annual Energy Savings (Net Source MMBtu)',    'Multifamily',   'Target Segments - Net Realized Source Savings', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_MULTIFAMILY_ANNUAL_MMBTU',   'CES_SAVINGS_FACT_FORECAST', 'SEG_MULTIFAMILY_ANNUAL_MMBTU',   'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 57, 'Multifamily',             'Target Segments - Net Realized Source Savings', 'Multifamily Lifetime Energy Savings (Net Source MMBtu)',  'Multifamily',   'Target Segments - Net Realized Source Savings', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_MULTIFAMILY_LIFETIME_MMBTU', 'CES_SAVINGS_FACT_FORECAST', 'SEG_MULTIFAMILY_LIFETIME_MMBTU', 'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 58, 'Residential LMI or OBC',  'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Annual Electric Savings - kWh',   'Residential LMI or OBC',  'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_RES_LMI_OBC_ELEC_ANNUAL_KWH',    'CES_SAVINGS_FACT_FORECAST', 'SEG_RES_LMI_OBC_ELEC_ANNUAL_KWH',    'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 59, 'Residential LMI or OBC',  'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Lifetime Electric Savings - kWh', 'Residential LMI or OBC',  'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_RES_LMI_OBC_ELEC_LIFETIME_KWH',  'CES_SAVINGS_FACT_FORECAST', 'SEG_RES_LMI_OBC_ELEC_LIFETIME_KWH',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 60, 'Residential LMI or OBC',  'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Annual Gas Savings - Therms',     'Residential LMI or OBC',  'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_RES_LMI_OBC_GAS_ANNUAL_THERMS',  'CES_SAVINGS_FACT_FORECAST', 'SEG_RES_LMI_OBC_GAS_ANNUAL_THERMS',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 61, 'Residential LMI or OBC',  'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Lifetime Gas Savings - Therms',   'Residential LMI or OBC',  'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_RES_LMI_OBC_GAS_LIFETIME_THERMS','CES_SAVINGS_FACT_FORECAST', 'SEG_RES_LMI_OBC_GAS_LIFETIME_THERMS','NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 62, 'Residential LMI Only',    'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Annual Electric Savings - kWh',   'Residential LMI Only',    'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_RES_LMI_ELEC_ANNUAL_KWH',    'CES_SAVINGS_FACT_FORECAST', 'SEG_RES_LMI_ELEC_ANNUAL_KWH',    'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 63, 'Residential LMI Only',    'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Lifetime Electric Savings - kWh', 'Residential LMI Only',    'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_RES_LMI_ELEC_LIFETIME_KWH',  'CES_SAVINGS_FACT_FORECAST', 'SEG_RES_LMI_ELEC_LIFETIME_KWH',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 64, 'Residential LMI Only',    'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Annual Gas Savings - Therms',     'Residential LMI Only',    'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_RES_LMI_GAS_ANNUAL_THERMS',  'CES_SAVINGS_FACT_FORECAST', 'SEG_RES_LMI_GAS_ANNUAL_THERMS',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 65, 'Residential LMI Only',    'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Lifetime Gas Savings - Therms',   'Residential LMI Only',    'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_RES_LMI_GAS_LIFETIME_THERMS','CES_SAVINGS_FACT_FORECAST', 'SEG_RES_LMI_GAS_LIFETIME_THERMS','NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 66, 'OBC Only (All Projects)', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Annual Electric Savings - kWh',   'OBC Only (All Projects)', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_OBC_ELEC_ANNUAL_KWH',    'CES_SAVINGS_FACT_FORECAST', 'SEG_OBC_ELEC_ANNUAL_KWH',    'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 67, 'OBC Only (All Projects)', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Lifetime Electric Savings - kWh', 'OBC Only (All Projects)', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_OBC_ELEC_LIFETIME_KWH',  'CES_SAVINGS_FACT_FORECAST', 'SEG_OBC_ELEC_LIFETIME_KWH',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 68, 'OBC Only (All Projects)', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Annual Gas Savings - Therms',     'OBC Only (All Projects)', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_OBC_GAS_ANNUAL_THERMS',  'CES_SAVINGS_FACT_FORECAST', 'SEG_OBC_GAS_ANNUAL_THERMS',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 69, 'OBC Only (All Projects)', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Lifetime Gas Savings - Therms',   'OBC Only (All Projects)', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_OBC_GAS_LIFETIME_THERMS','CES_SAVINGS_FACT_FORECAST', 'SEG_OBC_GAS_LIFETIME_THERMS','NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 70, 'Small Business', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Annual Electric Savings - kWh',   'Small Business', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_SMALL_BIZ_ELEC_ANNUAL_KWH',    'CES_SAVINGS_FACT_FORECAST', 'SEG_SMALL_BIZ_ELEC_ANNUAL_KWH',    'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 71, 'Small Business', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Lifetime Electric Savings - kWh', 'Small Business', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_SMALL_BIZ_ELEC_LIFETIME_KWH',  'CES_SAVINGS_FACT_FORECAST', 'SEG_SMALL_BIZ_ELEC_LIFETIME_KWH',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 72, 'Small Business', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Annual Gas Savings - Therms',     'Small Business', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_SMALL_BIZ_GAS_ANNUAL_THERMS',  'CES_SAVINGS_FACT_FORECAST', 'SEG_SMALL_BIZ_GAS_ANNUAL_THERMS',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 73, 'Small Business', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Lifetime Gas Savings - Therms',   'Small Business', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_SMALL_BIZ_GAS_LIFETIME_THERMS','CES_SAVINGS_FACT_FORECAST', 'SEG_SMALL_BIZ_GAS_LIFETIME_THERMS','NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 74, 'Multifamily', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Annual Electric Savings - kWh',   'Multifamily', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_MULTIFAMILY_ELEC_ANNUAL_KWH',    'CES_SAVINGS_FACT_FORECAST', 'SEG_MULTIFAMILY_ELEC_ANNUAL_KWH',    'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 75, 'Multifamily', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Lifetime Electric Savings - kWh', 'Multifamily', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_MULTIFAMILY_ELEC_LIFETIME_KWH',  'CES_SAVINGS_FACT_FORECAST', 'SEG_MULTIFAMILY_ELEC_LIFETIME_KWH',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 76, 'Multifamily', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Annual Gas Savings - Therms',     'Multifamily', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_MULTIFAMILY_GAS_ANNUAL_THERMS',  'CES_SAVINGS_FACT_FORECAST', 'SEG_MULTIFAMILY_GAS_ANNUAL_THERMS',  'NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL UNION ALL
SELECT 'Savings Forecast', 77, 'Multifamily', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 'Net Realized Site Lifetime Gas Savings - Therms',   'Multifamily', 'Target Segments - Net Realized Site Savings (Exclude Negative IEs)', 75, 'CES_SAVINGS_STG_FORECAST', 'SEG_MULTIFAMILY_GAS_LIFETIME_THERMS','CES_SAVINGS_FACT_FORECAST', 'SEG_MULTIFAMILY_GAS_LIFETIME_THERMS','NUMBER_4', 'N', 'N', 'N', 'Y' FROM DUAL
) s
ON (
    t.SHEET_NAME     = s.SHEET_NAME
AND t.STG_COLUMN_NAME = s.STG_COLUMN_NAME
)
WHEN MATCHED THEN UPDATE SET
    t.EXCEL_COL_POSITION = s.EXCEL_COL_POSITION,
    t.EXCEL_ROW1_HEADER  = s.EXCEL_ROW1_HEADER,
    t.EXCEL_ROW2_HEADER  = s.EXCEL_ROW2_HEADER,
    t.EXCEL_ROW3_HEADER  = s.EXCEL_ROW3_HEADER,
    t.ROW1_EXPECTED      = s.ROW1_EXPECTED,
    t.ROW2_EXPECTED      = s.ROW2_EXPECTED,
    t.FUZZY_THRESHOLD    = s.FUZZY_THRESHOLD,
    t.STG_TABLE_NAME     = s.STG_TABLE_NAME,
    t.FACT_TABLE_NAME    = s.FACT_TABLE_NAME,
    t.FACT_COLUMN_NAME   = s.FACT_COLUMN_NAME,
    t.DATA_TYPE          = s.DATA_TYPE,
    t.IS_DIMENSION       = s.IS_DIMENSION,
    t.IS_REQUIRED        = s.IS_REQUIRED,
    t.IS_STOP_COLUMN     = s.IS_STOP_COLUMN,
    t.IS_ACTIVE          = s.IS_ACTIVE,
    t.UPDATED_DATE       = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
    SHEET_NAME, EXCEL_COL_POSITION,
    EXCEL_ROW1_HEADER, EXCEL_ROW2_HEADER, EXCEL_ROW3_HEADER,
    ROW1_EXPECTED, ROW2_EXPECTED, FUZZY_THRESHOLD,
    STG_TABLE_NAME, STG_COLUMN_NAME,
    FACT_TABLE_NAME, FACT_COLUMN_NAME,
    DATA_TYPE, IS_DIMENSION, IS_REQUIRED,
    IS_STOP_COLUMN, IS_ACTIVE
) VALUES (
    s.SHEET_NAME, s.EXCEL_COL_POSITION,
    s.EXCEL_ROW1_HEADER, s.EXCEL_ROW2_HEADER, s.EXCEL_ROW3_HEADER,
    s.ROW1_EXPECTED, s.ROW2_EXPECTED, s.FUZZY_THRESHOLD,
    s.STG_TABLE_NAME, s.STG_COLUMN_NAME,
    s.FACT_TABLE_NAME, s.FACT_COLUMN_NAME,
    s.DATA_TYPE, s.IS_DIMENSION, s.IS_REQUIRED,
    s.IS_STOP_COLUMN, s.IS_ACTIVE
);

COMMIT;

-- Verify
SELECT SHEET_NAME, COUNT(*) TOTAL_ROWS
FROM   CES_SAVINGS_COLUMN_MAP
GROUP BY SHEET_NAME
ORDER BY SHEET_NAME;
-- ============================================================
