-- ============================================================
-- CES SAVINGS COLUMN MAP - V2
-- Adds index-based mapping + fuzzy threshold columns
-- Seed data with exact column indexes from screenshots
-- ============================================================

-- ============================================================
-- STEP 1: ALTER TABLE - add new columns
-- ============================================================

-- EXCEL_COL_POSITION already exists - just ensure it's there
-- If it doesn't exist uncomment this:
-- ALTER TABLE CES_SAVINGS_COLUMN_MAP ADD EXCEL_COL_POSITION NUMBER;

-- Add fuzzy threshold column
ALTER TABLE CES_SAVINGS_COLUMN_MAP
    ADD FUZZY_THRESHOLD NUMBER(5,2) DEFAULT 75;

-- Add expected row1/row2 columns for confidence bonus
ALTER TABLE CES_SAVINGS_COLUMN_MAP
    ADD ROW1_EXPECTED VARCHAR2(500);

ALTER TABLE CES_SAVINGS_COLUMN_MAP
    ADD ROW2_EXPECTED VARCHAR2(500);

COMMENT ON COLUMN CES_SAVINGS_COLUMN_MAP.EXCEL_COL_POSITION IS
    'PRIMARY lookup key. 1-based column index from Excel. Guaranteed by stakeholder column order agreement.';
COMMENT ON COLUMN CES_SAVINGS_COLUMN_MAP.FUZZY_THRESHOLD IS
    'Minimum fuzzy match score for row3 header validation. Default 75. Lower = more lenient.';
COMMENT ON COLUMN CES_SAVINGS_COLUMN_MAP.ROW1_EXPECTED IS
    'Expected row1 header for confidence bonus scoring (5 pts). Unreliable due to merged cells.';
COMMENT ON COLUMN CES_SAVINGS_COLUMN_MAP.ROW2_EXPECTED IS
    'Expected row2 header for confidence bonus scoring (5 pts). Unreliable due to merged cells.';


-- ============================================================
-- STEP 2: UPDATE existing rows with indexes + expected headers
-- Savings Results sheet
-- Indexes from screenshots (1-based)
-- ============================================================

-- Dimension columns (no row1/row2 context)
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=1,  ROW1_EXPECTED='', ROW2_EXPECTED='' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='TRIENNIUM';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=2,  ROW1_EXPECTED='', ROW2_EXPECTED='' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SECTOR';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=3,  ROW1_EXPECTED='', ROW2_EXPECTED='' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='VENDOR_SUBPROGRAM_KEY';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=4,  ROW1_EXPECTED='', ROW2_EXPECTED='' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='PROGRAM';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=5,  ROW1_EXPECTED='', ROW2_EXPECTED='' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SUBPROGRAM';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=6,  ROW1_EXPECTED='', ROW2_EXPECTED='' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='PROGRAM_YEAR';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=7,  ROW1_EXPECTED='', ROW2_EXPECTED='' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='REPORTING_PERIOD';

-- Financials (row2=Financials, no row1)
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=9,  ROW1_EXPECTED='', ROW2_EXPECTED='Financials' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='INVEST_COST_REBATE';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=10, ROW1_EXPECTED='', ROW2_EXPECTED='Financials' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='INVEST_COST_OBR';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=11, ROW1_EXPECTED='', ROW2_EXPECTED='Financials' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='INVEST_COST_OTHER';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=12, ROW1_EXPECTED='', ROW2_EXPECTED='Financials' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='TOTAL_INVEST_COST';

-- Participants (row2=Participants, no row1)
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=14, ROW1_EXPECTED='', ROW2_EXPECTED='Participants' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='PARTICIPANTS_TOTAL';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=15, ROW1_EXPECTED='', ROW2_EXPECTED='Participants' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='PARTICIPANTS_RES_LMI_OBC';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=16, ROW1_EXPECTED='', ROW2_EXPECTED='Participants' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='PARTICIPANTS_RES_LMI_ONLY';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=17, ROW1_EXPECTED='', ROW2_EXPECTED='Participants' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='PARTICIPANTS_OBC_ONLY';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=18, ROW1_EXPECTED='', ROW2_EXPECTED='Participants' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='PARTICIPANTS_SMALL_BIZ';

-- Gross Site Electric (row1=Electric, row2=Gross Site Savings TRM)
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=20, ROW1_EXPECTED='Electric',    ROW2_EXPECTED='Gross Site Savings (Exclude IEs) TRM Protocol' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='GROSS_SITE_ELEC_ANNUAL_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=21, ROW1_EXPECTED='Electric',    ROW2_EXPECTED='Gross Site Savings (Exclude IEs) TRM Protocol' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='GROSS_SITE_ELEC_DEMAND_KW';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=22, ROW1_EXPECTED='Electric',    ROW2_EXPECTED='Gross Site Savings (Exclude IEs) TRM Protocol' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='GROSS_SITE_ELEC_LIFETIME_KWH';

-- Gross Site Gas (row1=Natural Gas, row2=Gross Site Savings TRM)
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=23, ROW1_EXPECTED='Natural Gas', ROW2_EXPECTED='Gross Site Savings (Exclude IEs) TRM Protocol' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='GROSS_SITE_GAS_ANNUAL_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=24, ROW1_EXPECTED='Natural Gas', ROW2_EXPECTED='Gross Site Savings (Exclude IEs) TRM Protocol' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='GROSS_SITE_GAS_DAILY_PEAK_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=25, ROW1_EXPECTED='Natural Gas', ROW2_EXPECTED='Gross Site Savings (Exclude IEs) TRM Protocol' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='GROSS_SITE_GAS_LIFETIME_THERMS';

-- Net Site ISR Electric (row1=Electric, row2=Net Realized Site TRM x ISR)
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=26, ROW1_EXPECTED='Electric',    ROW2_EXPECTED='Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='NET_SITE_ISR_ELEC_ANNUAL_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=27, ROW1_EXPECTED='Electric',    ROW2_EXPECTED='Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='NET_SITE_ISR_ELEC_DEMAND_KW';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=28, ROW1_EXPECTED='Electric',    ROW2_EXPECTED='Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='NET_SITE_ISR_ELEC_LIFETIME_KWH';

-- Net Site ISR Gas (row1=Natural Gas, row2=Net Realized Site TRM x ISR)
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=29, ROW1_EXPECTED='Natural Gas', ROW2_EXPECTED='Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='NET_SITE_ISR_GAS_ANNUAL_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=30, ROW1_EXPECTED='Natural Gas', ROW2_EXPECTED='Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='NET_SITE_ISR_GAS_DAILY_PEAK_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=31, ROW1_EXPECTED='Natural Gas', ROW2_EXPECTED='Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='NET_SITE_ISR_GAS_LIFETIME_THERMS';

-- Negative IEs Electric
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=32, ROW1_EXPECTED='Electric',    ROW2_EXPECTED='Negative Interactive Effects (IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='NEG_IE_ELEC_ANNUAL_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=33, ROW1_EXPECTED='Electric',    ROW2_EXPECTED='Negative Interactive Effects (IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='NEG_IE_ELEC_LIFETIME_KWH';

-- Negative IEs Gas
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=34, ROW1_EXPECTED='Natural Gas', ROW2_EXPECTED='Negative Interactive Effects (IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='NEG_IE_GAS_ANNUAL_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=35, ROW1_EXPECTED='Natural Gas', ROW2_EXPECTED='Negative Interactive Effects (IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='NEG_IE_GAS_LIFETIME_THERMS';

-- Total Net Site Electric
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=36, ROW1_EXPECTED='Electric',    ROW2_EXPECTED='Total Net Realized Site Savings (Include Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='TOTAL_NET_SITE_ELEC_ANNUAL_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=37, ROW1_EXPECTED='Electric',    ROW2_EXPECTED='Total Net Realized Site Savings (Include Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='TOTAL_NET_SITE_ELEC_LIFETIME_KWH';

-- Total Net Site Gas
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=38, ROW1_EXPECTED='Natural Gas', ROW2_EXPECTED='Total Net Realized Site Savings (Include Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='TOTAL_NET_SITE_GAS_ANNUAL_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=39, ROW1_EXPECTED='Natural Gas', ROW2_EXPECTED='Total Net Realized Site Savings (Include Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='TOTAL_NET_SITE_GAS_LIFETIME_THERMS';

-- Net Source Electric
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=40, ROW1_EXPECTED='Electric',    ROW2_EXPECTED='Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='NET_SRC_ELEC_ANNUAL_MMBTU';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=41, ROW1_EXPECTED='Electric',    ROW2_EXPECTED='Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='NET_SRC_ELEC_LIFETIME_MMBTU';

-- Net Source Gas
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=42, ROW1_EXPECTED='Natural Gas', ROW2_EXPECTED='Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='NET_SRC_GAS_ANNUAL_MMBTU';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=43, ROW1_EXPECTED='Natural Gas', ROW2_EXPECTED='Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='NET_SRC_GAS_LIFETIME_MMBTU';

-- Net Source Total (Elec and Gas)
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=44, ROW1_EXPECTED='Elec and Gas Total', ROW2_EXPECTED='Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='NET_SRC_ANNUAL_MMBTU';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=45, ROW1_EXPECTED='Elec and Gas Total', ROW2_EXPECTED='Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='NET_SRC_LIFETIME_MMBTU';

-- Target Segments Source - LMI OBC
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=46, ROW1_EXPECTED='Residential LMI or OBC', ROW2_EXPECTED='Target Segments - Net Realized Source Savings' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_LMI_OBC_ANNUAL_MMBTU';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=47, ROW1_EXPECTED='Residential LMI or OBC', ROW2_EXPECTED='Target Segments - Net Realized Source Savings' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_LMI_OBC_LIFETIME_MMBTU';

-- Target Segments Source - LMI Only
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=48, ROW1_EXPECTED='Residential LMI Only', ROW2_EXPECTED='Target Segments - Net Realized Source Savings' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_LMI_ANNUAL_MMBTU';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=49, ROW1_EXPECTED='Residential LMI Only', ROW2_EXPECTED='Target Segments - Net Realized Source Savings' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_LMI_LIFETIME_MMBTU';

-- Target Segments Source - OBC Only
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=50, ROW1_EXPECTED='OBC Only (All Projects)', ROW2_EXPECTED='Target Segments - Net Realized Source Savings' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_OBC_ANNUAL_MMBTU';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=51, ROW1_EXPECTED='OBC Only (All Projects)', ROW2_EXPECTED='Target Segments - Net Realized Source Savings' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_OBC_LIFETIME_MMBTU';

-- Target Segments Source - Small Business
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=52, ROW1_EXPECTED='Small Business', ROW2_EXPECTED='Target Segments - Net Realized Source Savings' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_SMALL_BIZ_ANNUAL_MMBTU';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=53, ROW1_EXPECTED='Small Business', ROW2_EXPECTED='Target Segments - Net Realized Source Savings' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_SMALL_BIZ_LIFETIME_MMBTU';

-- Target Segments Source - Multifamily
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=54, ROW1_EXPECTED='Multifamily', ROW2_EXPECTED='Target Segments - Net Realized Source Savings' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_MULTIFAMILY_ANNUAL_MMBTU';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=55, ROW1_EXPECTED='Multifamily', ROW2_EXPECTED='Target Segments - Net Realized Source Savings' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_MULTIFAMILY_LIFETIME_MMBTU';

-- Target Segments Site - Residential LMI or OBC
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=56, ROW1_EXPECTED='Residential LMI or OBC', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_RES_LMI_OBC_ELEC_ANNUAL_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=57, ROW1_EXPECTED='Residential LMI or OBC', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_RES_LMI_OBC_ELEC_LIFETIME_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=58, ROW1_EXPECTED='Residential LMI or OBC', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_RES_LMI_OBC_GAS_ANNUAL_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=59, ROW1_EXPECTED='Residential LMI or OBC', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_RES_LMI_OBC_GAS_LIFETIME_THERMS';

-- Target Segments Site - Residential LMI Only
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=60, ROW1_EXPECTED='Residential LMI Only', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_RES_LMI_ELEC_ANNUAL_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=61, ROW1_EXPECTED='Residential LMI Only', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_RES_LMI_ELEC_LIFETIME_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=62, ROW1_EXPECTED='Residential LMI Only', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_RES_LMI_GAS_ANNUAL_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=63, ROW1_EXPECTED='Residential LMI Only', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_RES_LMI_GAS_LIFETIME_THERMS';

-- Target Segments Site - OBC Only
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=64, ROW1_EXPECTED='OBC Only (All Projects)', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_OBC_ELEC_ANNUAL_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=65, ROW1_EXPECTED='OBC Only (All Projects)', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_OBC_ELEC_LIFETIME_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=66, ROW1_EXPECTED='OBC Only (All Projects)', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_OBC_GAS_ANNUAL_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=67, ROW1_EXPECTED='OBC Only (All Projects)', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_OBC_GAS_LIFETIME_THERMS';

-- Target Segments Site - Small Business
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=68, ROW1_EXPECTED='Small Business', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_SMALL_BIZ_ELEC_ANNUAL_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=69, ROW1_EXPECTED='Small Business', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_SMALL_BIZ_ELEC_LIFETIME_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=70, ROW1_EXPECTED='Small Business', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_SMALL_BIZ_GAS_ANNUAL_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=71, ROW1_EXPECTED='Small Business', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_SMALL_BIZ_GAS_LIFETIME_THERMS';

-- Target Segments Site - Multifamily
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=72, ROW1_EXPECTED='Multifamily', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_MULTIFAMILY_ELEC_ANNUAL_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=73, ROW1_EXPECTED='Multifamily', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_MULTIFAMILY_ELEC_LIFETIME_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=74, ROW1_EXPECTED='Multifamily', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_MULTIFAMILY_GAS_ANNUAL_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=75, ROW1_EXPECTED='Multifamily', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Results' AND STG_COLUMN_NAME='SEG_MULTIFAMILY_GAS_LIFETIME_THERMS';


-- ============================================================
-- STEP 3: Savings Forecast - same columns + 2 extra
-- Forecast Period at index 8 (replaces Reporting Period at 7)
-- Confidence Level at index 9
-- All metric columns shift by 2 (extra Forecast Period + Confidence Level)
-- ============================================================

-- Dimension columns
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=1,  ROW1_EXPECTED='', ROW2_EXPECTED='' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='TRIENNIUM';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=2,  ROW1_EXPECTED='', ROW2_EXPECTED='' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SECTOR';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=3,  ROW1_EXPECTED='', ROW2_EXPECTED='' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='VENDOR_SUBPROGRAM_KEY';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=4,  ROW1_EXPECTED='', ROW2_EXPECTED='' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='PROGRAM';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=5,  ROW1_EXPECTED='', ROW2_EXPECTED='' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SUBPROGRAM';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=6,  ROW1_EXPECTED='', ROW2_EXPECTED='' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='PROGRAM_YEAR';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=7,  ROW1_EXPECTED='', ROW2_EXPECTED='' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='FORECAST_PERIOD';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=8,  ROW1_EXPECTED='', ROW2_EXPECTED='' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='CONFIDENCE_LEVEL';

-- Financials (shift +2 from actuals due to extra cols)
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=11, ROW1_EXPECTED='', ROW2_EXPECTED='Financials' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='INVEST_COST_REBATE';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=12, ROW1_EXPECTED='', ROW2_EXPECTED='Financials' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='INVEST_COST_OBR';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=13, ROW1_EXPECTED='', ROW2_EXPECTED='Financials' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='INVEST_COST_OTHER';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=14, ROW1_EXPECTED='', ROW2_EXPECTED='Financials' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='TOTAL_INVEST_COST';

-- Participants
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=16, ROW1_EXPECTED='', ROW2_EXPECTED='Participants' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='PARTICIPANTS_TOTAL';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=17, ROW1_EXPECTED='', ROW2_EXPECTED='Participants' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='PARTICIPANTS_RES_LMI_OBC';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=18, ROW1_EXPECTED='', ROW2_EXPECTED='Participants' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='PARTICIPANTS_RES_LMI_ONLY';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=19, ROW1_EXPECTED='', ROW2_EXPECTED='Participants' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='PARTICIPANTS_OBC_ONLY';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=20, ROW1_EXPECTED='', ROW2_EXPECTED='Participants' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='PARTICIPANTS_SMALL_BIZ';

-- Gross Site Electric
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=22, ROW1_EXPECTED='Electric',    ROW2_EXPECTED='Gross Site Savings (Exclude IEs) TRM Protocol' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='GROSS_SITE_ELEC_ANNUAL_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=23, ROW1_EXPECTED='Electric',    ROW2_EXPECTED='Gross Site Savings (Exclude IEs) TRM Protocol' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='GROSS_SITE_ELEC_DEMAND_KW';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=24, ROW1_EXPECTED='Electric',    ROW2_EXPECTED='Gross Site Savings (Exclude IEs) TRM Protocol' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='GROSS_SITE_ELEC_LIFETIME_KWH';

-- Gross Site Gas
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=25, ROW1_EXPECTED='Natural Gas', ROW2_EXPECTED='Gross Site Savings (Exclude IEs) TRM Protocol' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='GROSS_SITE_GAS_ANNUAL_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=26, ROW1_EXPECTED='Natural Gas', ROW2_EXPECTED='Gross Site Savings (Exclude IEs) TRM Protocol' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='GROSS_SITE_GAS_DAILY_PEAK_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=27, ROW1_EXPECTED='Natural Gas', ROW2_EXPECTED='Gross Site Savings (Exclude IEs) TRM Protocol' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='GROSS_SITE_GAS_LIFETIME_THERMS';

-- Net Site ISR Electric
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=28, ROW1_EXPECTED='Electric',    ROW2_EXPECTED='Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='NET_SITE_ISR_ELEC_ANNUAL_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=29, ROW1_EXPECTED='Electric',    ROW2_EXPECTED='Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='NET_SITE_ISR_ELEC_DEMAND_KW';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=30, ROW1_EXPECTED='Electric',    ROW2_EXPECTED='Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='NET_SITE_ISR_ELEC_LIFETIME_KWH';

-- Net Site ISR Gas
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=31, ROW1_EXPECTED='Natural Gas', ROW2_EXPECTED='Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='NET_SITE_ISR_GAS_ANNUAL_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=32, ROW1_EXPECTED='Natural Gas', ROW2_EXPECTED='Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='NET_SITE_ISR_GAS_DAILY_PEAK_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=33, ROW1_EXPECTED='Natural Gas', ROW2_EXPECTED='Net Realized Site Savings (Exclude Negative IEs) TRM Protocol x ISR' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='NET_SITE_ISR_GAS_LIFETIME_THERMS';

-- Negative IEs
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=34, ROW1_EXPECTED='Electric',    ROW2_EXPECTED='Negative Interactive Effects (IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='NEG_IE_ELEC_ANNUAL_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=35, ROW1_EXPECTED='Electric',    ROW2_EXPECTED='Negative Interactive Effects (IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='NEG_IE_ELEC_LIFETIME_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=36, ROW1_EXPECTED='Natural Gas', ROW2_EXPECTED='Negative Interactive Effects (IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='NEG_IE_GAS_ANNUAL_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=37, ROW1_EXPECTED='Natural Gas', ROW2_EXPECTED='Negative Interactive Effects (IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='NEG_IE_GAS_LIFETIME_THERMS';

-- Total Net Site
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=38, ROW1_EXPECTED='Electric',    ROW2_EXPECTED='Total Net Realized Site Savings (Include Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='TOTAL_NET_SITE_ELEC_ANNUAL_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=39, ROW1_EXPECTED='Electric',    ROW2_EXPECTED='Total Net Realized Site Savings (Include Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='TOTAL_NET_SITE_ELEC_LIFETIME_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=40, ROW1_EXPECTED='Natural Gas', ROW2_EXPECTED='Total Net Realized Site Savings (Include Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='TOTAL_NET_SITE_GAS_ANNUAL_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=41, ROW1_EXPECTED='Natural Gas', ROW2_EXPECTED='Total Net Realized Site Savings (Include Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='TOTAL_NET_SITE_GAS_LIFETIME_THERMS';

-- Net Source
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=42, ROW1_EXPECTED='Electric',          ROW2_EXPECTED='Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='NET_SRC_ELEC_ANNUAL_MMBTU';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=43, ROW1_EXPECTED='Electric',          ROW2_EXPECTED='Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='NET_SRC_ELEC_LIFETIME_MMBTU';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=44, ROW1_EXPECTED='Natural Gas',       ROW2_EXPECTED='Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='NET_SRC_GAS_ANNUAL_MMBTU';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=45, ROW1_EXPECTED='Natural Gas',       ROW2_EXPECTED='Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='NET_SRC_GAS_LIFETIME_MMBTU';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=46, ROW1_EXPECTED='Elec and Gas Total', ROW2_EXPECTED='Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='NET_SRC_ANNUAL_MMBTU';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=47, ROW1_EXPECTED='Elec and Gas Total', ROW2_EXPECTED='Net Realized Source Savings (Includes Negative IEs) TRM x ISR x RR x NTG x Source Conversion' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='NET_SRC_LIFETIME_MMBTU';

-- Target Segments Source
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=48, ROW1_EXPECTED='Residential LMI or OBC',  ROW2_EXPECTED='Target Segments - Net Realized Source Savings' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_LMI_OBC_ANNUAL_MMBTU';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=49, ROW1_EXPECTED='Residential LMI or OBC',  ROW2_EXPECTED='Target Segments - Net Realized Source Savings' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_LMI_OBC_LIFETIME_MMBTU';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=50, ROW1_EXPECTED='Residential LMI Only',    ROW2_EXPECTED='Target Segments - Net Realized Source Savings' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_LMI_ANNUAL_MMBTU';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=51, ROW1_EXPECTED='Residential LMI Only',    ROW2_EXPECTED='Target Segments - Net Realized Source Savings' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_LMI_LIFETIME_MMBTU';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=52, ROW1_EXPECTED='OBC Only (All Projects)', ROW2_EXPECTED='Target Segments - Net Realized Source Savings' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_OBC_ANNUAL_MMBTU';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=53, ROW1_EXPECTED='OBC Only (All Projects)', ROW2_EXPECTED='Target Segments - Net Realized Source Savings' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_OBC_LIFETIME_MMBTU';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=54, ROW1_EXPECTED='Small Business',          ROW2_EXPECTED='Target Segments - Net Realized Source Savings' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_SMALL_BIZ_ANNUAL_MMBTU';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=55, ROW1_EXPECTED='Small Business',          ROW2_EXPECTED='Target Segments - Net Realized Source Savings' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_SMALL_BIZ_LIFETIME_MMBTU';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=56, ROW1_EXPECTED='Multifamily',             ROW2_EXPECTED='Target Segments - Net Realized Source Savings' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_MULTIFAMILY_ANNUAL_MMBTU';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=57, ROW1_EXPECTED='Multifamily',             ROW2_EXPECTED='Target Segments - Net Realized Source Savings' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_MULTIFAMILY_LIFETIME_MMBTU';

-- Target Segments Site
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=58, ROW1_EXPECTED='Residential LMI or OBC',  ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_RES_LMI_OBC_ELEC_ANNUAL_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=59, ROW1_EXPECTED='Residential LMI or OBC',  ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_RES_LMI_OBC_ELEC_LIFETIME_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=60, ROW1_EXPECTED='Residential LMI or OBC',  ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_RES_LMI_OBC_GAS_ANNUAL_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=61, ROW1_EXPECTED='Residential LMI or OBC',  ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_RES_LMI_OBC_GAS_LIFETIME_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=62, ROW1_EXPECTED='Residential LMI Only',    ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_RES_LMI_ELEC_ANNUAL_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=63, ROW1_EXPECTED='Residential LMI Only',    ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_RES_LMI_ELEC_LIFETIME_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=64, ROW1_EXPECTED='Residential LMI Only',    ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_RES_LMI_GAS_ANNUAL_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=65, ROW1_EXPECTED='Residential LMI Only',    ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_RES_LMI_GAS_LIFETIME_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=66, ROW1_EXPECTED='OBC Only (All Projects)', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_OBC_ELEC_ANNUAL_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=67, ROW1_EXPECTED='OBC Only (All Projects)', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_OBC_ELEC_LIFETIME_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=68, ROW1_EXPECTED='OBC Only (All Projects)', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_OBC_GAS_ANNUAL_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=69, ROW1_EXPECTED='OBC Only (All Projects)', ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_OBC_GAS_LIFETIME_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=70, ROW1_EXPECTED='Small Business',          ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_SMALL_BIZ_ELEC_ANNUAL_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=71, ROW1_EXPECTED='Small Business',          ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_SMALL_BIZ_ELEC_LIFETIME_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=72, ROW1_EXPECTED='Small Business',          ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_SMALL_BIZ_GAS_ANNUAL_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=73, ROW1_EXPECTED='Small Business',          ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_SMALL_BIZ_GAS_LIFETIME_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=74, ROW1_EXPECTED='Multifamily',             ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_MULTIFAMILY_ELEC_ANNUAL_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=75, ROW1_EXPECTED='Multifamily',             ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_MULTIFAMILY_ELEC_LIFETIME_KWH';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=76, ROW1_EXPECTED='Multifamily',             ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_MULTIFAMILY_GAS_ANNUAL_THERMS';
UPDATE CES_SAVINGS_COLUMN_MAP SET EXCEL_COL_POSITION=77, ROW1_EXPECTED='Multifamily',             ROW2_EXPECTED='Target Segments - Net Realized Site Savings (Exclude Negative IEs)' WHERE SHEET_NAME='Savings Forecast' AND STG_COLUMN_NAME='SEG_MULTIFAMILY_GAS_LIFETIME_THERMS';

COMMIT;

-- ============================================================
-- VERIFICATION
-- ============================================================
SELECT
    SHEET_NAME,
    COUNT(*)                                              AS TOTAL,
    SUM(CASE WHEN EXCEL_COL_POSITION IS NOT NULL THEN 1 ELSE 0 END) AS WITH_INDEX,
    SUM(CASE WHEN EXCEL_COL_POSITION IS NULL     THEN 1 ELSE 0 END) AS WITHOUT_INDEX
FROM CES_SAVINGS_COLUMN_MAP
GROUP BY SHEET_NAME
ORDER BY SHEET_NAME;
-- ============================================================
