-- STG ACTUALS columns not in mapping
SELECT COLUMN_NAME
FROM   USER_TAB_COLUMNS
WHERE  TABLE_NAME = 'CES_SAVINGS_STG_ACTUALS'
AND    COLUMN_NAME NOT IN (
    'STG_ID','SOURCE_FILE_NAME',
    'BATCH_ID','LOAD_TIMESTAMP'
)
AND    COLUMN_NAME NOT IN (
    SELECT STG_COLUMN_NAME
    FROM   CES_SAVINGS_COLUMN_MAP
    WHERE  SHEET_NAME = 'Savings Results'
)
ORDER BY COLUMN_ID;

-- FACT ACTUALS columns not in mapping
SELECT COLUMN_NAME
FROM   USER_TAB_COLUMNS
WHERE  TABLE_NAME = 'CES_SAVINGS_FACT_ACTUALS'
AND    COLUMN_NAME NOT IN (
    'FACT_SK','VENDOR_SUBPROGRAM_SK','PERIOD_SK',
    'VENDOR_SUBPROGRAM_KEY','REPORTING_PERIOD',
    'SOURCE_FILE_NAME','BATCH_ID','LOAD_TIMESTAMP',
    'VERSION_NUMBER','IS_CURRENT_VERSION','DATA_DATE',
    'TRIENNIUM','SECTOR','PROGRAM','SUBPROGRAM',
    'PROGRAM_YEAR','CREATED_DATE','UPDATED_DATE',
    'CREATED_BY','UPDATED_BY'
)
AND    COLUMN_NAME NOT IN (
    SELECT FACT_COLUMN_NAME
    FROM   CES_SAVINGS_COLUMN_MAP
    WHERE  SHEET_NAME = 'Savings Results'
    AND    FACT_COLUMN_NAME IS NOT NULL
)
ORDER BY COLUMN_ID;

-- STG FORECAST columns not in mapping
SELECT COLUMN_NAME
FROM   USER_TAB_COLUMNS
WHERE  TABLE_NAME = 'CES_SAVINGS_STG_FORECAST'
AND    COLUMN_NAME NOT IN (
    'STG_ID','SOURCE_FILE_NAME',
    'BATCH_ID','LOAD_TIMESTAMP'
)
AND    COLUMN_NAME NOT IN (
    SELECT STG_COLUMN_NAME
    FROM   CES_SAVINGS_COLUMN_MAP
    WHERE  SHEET_NAME = 'Savings Forecast'
)
ORDER BY COLUMN_ID;

-- FACT FORECAST columns not in mapping
SELECT COLUMN_NAME
FROM   USER_TAB_COLUMNS
WHERE  TABLE_NAME = 'CES_SAVINGS_FACT_FORECAST'
AND    COLUMN_NAME NOT IN (
    'FACT_SK','VENDOR_SUBPROGRAM_SK','PERIOD_SK',
    'VENDOR_SUBPROGRAM_KEY','FORECAST_PERIOD',
    'CONFIDENCE_LEVEL',
    'SOURCE_FILE_NAME','BATCH_ID','LOAD_TIMESTAMP',
    'VERSION_NUMBER','IS_CURRENT_VERSION','DATA_DATE',
    'TRIENNIUM','SECTOR','PROGRAM','SUBPROGRAM',
    'PROGRAM_YEAR','CREATED_DATE','UPDATED_DATE',
    'CREATED_BY','UPDATED_BY'
)
AND    COLUMN_NAME NOT IN (
    SELECT FACT_COLUMN_NAME
    FROM   CES_SAVINGS_COLUMN_MAP
    WHERE  SHEET_NAME = 'Savings Forecast'
    AND    FACT_COLUMN_NAME IS NOT NULL
)
ORDER BY COLUMN_ID;

